/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meta */
        get: operations["meta_api_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard */
        get: operations["dashboard_api_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Model Runs */
        get: operations["model_runs_api_models_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/sync-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Sync Status */
        get: operations["admin_sync_status_api_admin_sync_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Players */
        get: operations["list_players_api_players_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{player_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Player Detail */
        get: operations["player_detail_api_players__player_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{player_id}/ratings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Player Ratings */
        get: operations["player_ratings_api_players__player_id__ratings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{player_id}/similar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Similar */
        get: operations["similar_api_players__player_id__similar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/moneyball/undervalued": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Undervalued */
        get: operations["undervalued_api_moneyball_undervalued_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/moneyball/scatter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scatter */
        get: operations["scatter_api_moneyball_scatter_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fixtures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Fixtures */
        get: operations["list_fixtures_api_fixtures_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fixtures/{fixture_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fixture Detail */
        get: operations["fixture_detail_api_fixtures__fixture_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Teams */
        get: operations["list_teams_api_teams_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{team_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Team Detail */
        get: operations["team_detail_api_teams__team_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/managers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Managers */
        get: operations["list_managers_api_managers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/managers/{coach_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Manager Detail */
        get: operations["manager_detail_api_managers__coach_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Dashboard */
        Dashboard: {
            /** Round */
            round?: string | null;
            /** Team Of The Week */
            team_of_the_week: components["schemas"]["TeamOfWeekPlayer"][];
            /** In Form */
            in_form: components["schemas"]["PlayerRow"][];
            /** Undervalued */
            undervalued: components["schemas"]["PlayerRow"][];
            /** Upcoming */
            upcoming: components["schemas"]["FixtureRow"][];
            latest_run?: components["schemas"]["ModelRunOut"] | null;
        };
        /** FixtureDetail */
        FixtureDetail: {
            fixture: components["schemas"]["FixtureRow"];
            /** Lineups */
            lineups: {
                [key: string]: components["schemas"]["LineupPlayer"][];
            };
        };
        /** FixtureRow */
        FixtureRow: {
            /** Id */
            id: number;
            /**
             * Date
             * Format: date-time
             */
            date: string;
            /** Round */
            round?: string | null;
            /** Status */
            status: string;
            home: components["schemas"]["TeamRef"];
            away: components["schemas"]["TeamRef"];
            /** Home Goals */
            home_goals?: number | null;
            /** Away Goals */
            away_goals?: number | null;
            prediction?: components["schemas"]["Prediction"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LineupPlayer */
        LineupPlayer: {
            /** Player Id */
            player_id: number;
            /** Name */
            name: string;
            /** Photo */
            photo?: string | null;
            /** Position */
            position?: string | null;
            /** Minutes */
            minutes: number;
            /** Substitute */
            substitute: boolean;
            /** Rating */
            rating?: number | null;
            /** Api Rating */
            api_rating?: number | null;
            /**
             * Components
             * @default {}
             */
            components: {
                [key: string]: number;
            };
            /** Goals */
            goals: number;
            /** Assists */
            assists: number;
        };
        /** ManagerDetail */
        ManagerDetail: {
            manager: components["schemas"]["ManagerRow"];
            /** Nationality */
            nationality?: string | null;
            /** Series */
            series: components["schemas"]["ManagerPoint"][];
        };
        /** ManagerPoint */
        ManagerPoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Pts */
            pts: number;
            /** Xpts */
            xpts: number;
        };
        /** ManagerRow */
        ManagerRow: {
            /** Coach Id */
            coach_id: number;
            /** Name */
            name: string;
            /** Photo */
            photo?: string | null;
            team: components["schemas"]["TeamRef"];
            /** Tenure Start */
            tenure_start?: string | null;
            /** Matches */
            matches: number;
            /** Ppg */
            ppg: number;
            /** Xppg */
            xppg: number;
            /** Pts Over Exp */
            pts_over_exp: number;
            /** Squad Efficiency */
            squad_efficiency?: number | null;
            /** Development */
            development?: number | null;
            /** Score */
            score: number;
        };
        /** Meta */
        Meta: {
            /** Leagues */
            leagues: number[];
            /** Season */
            season: number;
            /** Teams */
            teams: components["schemas"]["TeamRef"][];
            latest_run?: components["schemas"]["ModelRunOut"] | null;
        };
        /** ModelRunOut */
        ModelRunOut: {
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Status */
            status: string;
            /** Git Sha */
            git_sha?: string | null;
            /** Data Cutoff */
            data_cutoff?: string | null;
            /** Mlflow Run Id */
            mlflow_run_id?: string | null;
            /** Metrics */
            metrics: {
                [key: string]: unknown;
            };
        };
        /** PlayerDetail */
        PlayerDetail: {
            player: components["schemas"]["PlayerRow"];
            /** Nationality */
            nationality?: string | null;
            /** Birth Date */
            birth_date?: string | null;
            /** Height Cm */
            height_cm?: number | null;
            /** Profile Position */
            profile_position?: string | null;
            /** Form Sd */
            form_sd?: number | null;
            /** Per90 */
            per90: {
                [key: string]: number | null;
            };
            /** Shrunk Per90 */
            shrunk_per90: {
                [key: string]: number | null;
            };
            /** Percentiles */
            percentiles: {
                [key: string]: number | null;
            };
            valuation?: components["schemas"]["Valuation"] | null;
            /** Value History */
            value_history: components["schemas"]["ValuePoint"][];
            /** Contract Expiration */
            contract_expiration?: string | null;
        };
        /** PlayerRow */
        PlayerRow: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Photo */
            photo?: string | null;
            team?: components["schemas"]["TeamRef"] | null;
            /** Position Group */
            position_group: string;
            /** Age */
            age?: number | null;
            /** Apps */
            apps: number;
            /** Minutes */
            minutes: number;
            /** Goals */
            goals: number;
            /** Assists */
            assists: number;
            /** Avg Rating */
            avg_rating?: number | null;
            /** Form */
            form?: number | null;
            /** Expected Next */
            expected_next?: number | null;
            /** Perf Index */
            perf_index?: number | null;
            /** Market Value */
            market_value?: number | null;
            /** P50 */
            p50?: number | null;
            /** Undervalue Score */
            undervalue_score?: number | null;
        };
        /** Prediction */
        Prediction: {
            /** Home Win */
            home_win: number;
            /** Draw */
            draw: number;
            /** Away Win */
            away_win: number;
            /** Exp Home Goals */
            exp_home_goals: number;
            /** Exp Away Goals */
            exp_away_goals: number;
        };
        /** RatingPoint */
        RatingPoint: {
            /** Fixture Id */
            fixture_id: number;
            /**
             * Date
             * Format: date-time
             */
            date: string;
            opponent: components["schemas"]["TeamRef"];
            /** Home */
            home: boolean;
            /** Score */
            score: string;
            /** Minutes */
            minutes: number;
            /** Rating */
            rating: number;
            /** Api Rating */
            api_rating?: number | null;
            /** Form */
            form?: number | null;
            /** Form Lo */
            form_lo?: number | null;
            /** Form Hi */
            form_hi?: number | null;
            /** Components */
            components: {
                [key: string]: number;
            };
        };
        /** ScatterPoint */
        ScatterPoint: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Team */
            team?: string | null;
            /** Position Group */
            position_group: string;
            /** Age */
            age?: number | null;
            /** Perf Index */
            perf_index: number;
            /** Market Value */
            market_value: number;
            /** P10 */
            p10?: number | null;
            /** P50 */
            p50?: number | null;
            /** P90 */
            p90?: number | null;
            /** Undervalue Score */
            undervalue_score?: number | null;
        };
        /** SimilarRow */
        SimilarRow: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Photo */
            photo?: string | null;
            team?: components["schemas"]["TeamRef"] | null;
            /** Position Group */
            position_group: string;
            /** Age */
            age?: number | null;
            /** Apps */
            apps: number;
            /** Minutes */
            minutes: number;
            /** Goals */
            goals: number;
            /** Assists */
            assists: number;
            /** Avg Rating */
            avg_rating?: number | null;
            /** Form */
            form?: number | null;
            /** Expected Next */
            expected_next?: number | null;
            /** Perf Index */
            perf_index?: number | null;
            /** Market Value */
            market_value?: number | null;
            /** P50 */
            p50?: number | null;
            /** Undervalue Score */
            undervalue_score?: number | null;
            /** Similarity */
            similarity: number;
        };
        /** TeamDetail */
        TeamDetail: {
            team: components["schemas"]["TeamRow"];
            /** Series */
            series: components["schemas"]["TeamMatchPoint"][];
            /** Squad */
            squad: components["schemas"]["PlayerRow"][];
            /** Managers */
            managers: components["schemas"]["ManagerRow"][];
        };
        /** TeamMatchPoint */
        TeamMatchPoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Fixture Id */
            fixture_id: number;
            /** Opponent Id */
            opponent_id: number;
            /** Gf */
            gf: number;
            /** Ga */
            ga: number;
            /** Pts */
            pts: number;
            /** Xpts */
            xpts: number;
        };
        /** TeamOfWeekPlayer */
        TeamOfWeekPlayer: {
            /** Player Id */
            player_id: number;
            /** Name */
            name: string;
            /** Photo */
            photo?: string | null;
            team: components["schemas"]["TeamRef"];
            /** Position Group */
            position_group: string;
            /** Rating */
            rating: number;
        };
        /** TeamRef */
        TeamRef: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Logo */
            logo?: string | null;
        };
        /** TeamRow */
        TeamRow: {
            team: components["schemas"]["TeamRef"];
            /** Attack */
            attack?: number | null;
            /** Defence */
            defence?: number | null;
            /** Rating */
            rating?: number | null;
            /** Played */
            played?: number | null;
            /** Points */
            points?: number | null;
            /** Xpts */
            xpts?: number | null;
            /** Goals For */
            goals_for?: number | null;
            /** Goals Against */
            goals_against?: number | null;
            /** Avg Player Rating */
            avg_player_rating?: number | null;
            /** Squad Value */
            squad_value?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** Valuation */
        Valuation: {
            /** Market Value */
            market_value: number;
            /** P10 */
            p10: number;
            /** P50 */
            p50: number;
            /** P90 */
            p90: number;
            /** Undervalue Score */
            undervalue_score: number;
            /** Below P10 */
            below_p10: boolean;
            /** Contributions */
            contributions: {
                [key: string]: number;
            };
        };
        /** ValuePoint */
        ValuePoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Value */
            value: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    meta_api_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meta"];
                };
            };
        };
    };
    dashboard_api_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dashboard"];
                };
            };
        };
    };
    model_runs_api_models_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelRunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_sync_status_api_admin_sync_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_players_api_players_get: {
        parameters: {
            query?: {
                position?: ("GK" | "DEF" | "MID" | "FWD") | null;
                team_id?: number | null;
                age_max?: number | null;
                /** @description EUR */
                value_max?: number | null;
                min_minutes?: number;
                q?: string | null;
                sort?: "perf_index" | "form" | "avg_rating" | "market_value" | "minutes" | "goals" | "undervalue";
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    player_detail_api_players__player_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    player_ratings_api_players__player_id__ratings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatingPoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    similar_api_players__player_id__similar_get: {
        parameters: {
            query?: {
                max_value?: number | null;
                max_age?: number | null;
                limit?: number;
            };
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimilarRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    undervalued_api_moneyball_undervalued_get: {
        parameters: {
            query?: {
                position?: ("GK" | "DEF" | "MID" | "FWD") | null;
                age_max?: number | null;
                value_max?: number | null;
                min_minutes?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scatter_api_moneyball_scatter_get: {
        parameters: {
            query?: {
                position?: ("GK" | "DEF" | "MID" | "FWD") | null;
                min_minutes?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScatterPoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_fixtures_api_fixtures_get: {
        parameters: {
            query?: {
                status?: "upcoming" | "played";
                team_id?: number | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FixtureRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fixture_detail_api_fixtures__fixture_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fixture_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FixtureDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_teams_api_teams_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamRow"][];
                };
            };
        };
    };
    team_detail_api_teams__team_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_managers_api_managers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManagerRow"][];
                };
            };
        };
    };
    manager_detail_api_managers__coach_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                coach_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManagerDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
