"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-02 00:21:49.563610
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('endpoint', sa.String(length=60), nullable=False),
    sa.Column('params', sa.String(length=300), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('remaining', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_usage_day'), ['day'], unique=False)

    op.create_table('coaches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('nationality', sa.String(length=80), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('photo', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('logo', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manager_ratings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_run_id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('tenure_start', sa.Date(), nullable=True),
    sa.Column('matches', sa.Integer(), nullable=False),
    sa.Column('ppg', sa.Float(), nullable=False),
    sa.Column('xppg', sa.Float(), nullable=False),
    sa.Column('pts_over_exp', sa.Float(), nullable=False),
    sa.Column('squad_efficiency', sa.Float(), nullable=True),
    sa.Column('development', sa.Float(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('series', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('manager_ratings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_manager_ratings_coach_id'), ['coach_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_manager_ratings_score'), ['score'], unique=False)

    op.create_table('market_values',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tm_player_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value_eur', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('market_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_values_tm_player_id'), ['tm_player_id'], unique=False)

    op.create_table('match_predictions',
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('model_run_id', sa.Integer(), nullable=False),
    sa.Column('home_win', sa.Float(), nullable=False),
    sa.Column('draw', sa.Float(), nullable=False),
    sa.Column('away_win', sa.Float(), nullable=False),
    sa.Column('exp_home_goals', sa.Float(), nullable=False),
    sa.Column('exp_away_goals', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('fixture_id')
    )
    op.create_table('match_ratings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_run_id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('position_group', sa.String(length=3), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('raw_score', sa.Float(), nullable=False),
    sa.Column('components', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fixture_id', 'player_id')
    )
    with op.batch_alter_table('match_ratings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_ratings_fixture_id'), ['fixture_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_ratings_model_run_id'), ['model_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_ratings_player_id'), ['player_id'], unique=False)

    op.create_table('model_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('git_sha', sa.String(length=40), nullable=True),
    sa.Column('data_cutoff', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mlflow_run_id', sa.String(length=64), nullable=True),
    sa.Column('artifact_prefix', sa.String(length=200), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_form',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_run_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('form', sa.Float(), nullable=False),
    sa.Column('form_lo', sa.Float(), nullable=False),
    sa.Column('form_hi', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'fixture_id')
    )
    with op.batch_alter_table('player_form', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_form_player_id'), ['player_id'], unique=False)

    op.create_table('player_link_overrides',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('tm_player_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('player_links',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('tm_player_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('player_id')
    )
    with op.batch_alter_table('player_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_links_tm_player_id'), ['tm_player_id'], unique=False)

    op.create_table('player_season_agg',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('model_run_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('position_group', sa.String(length=3), nullable=False),
    sa.Column('age', sa.Float(), nullable=True),
    sa.Column('apps', sa.Integer(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('avg_rating', sa.Float(), nullable=True),
    sa.Column('form', sa.Float(), nullable=True),
    sa.Column('form_sd', sa.Float(), nullable=True),
    sa.Column('expected_next', sa.Float(), nullable=True),
    sa.Column('perf_index', sa.Float(), nullable=True),
    sa.Column('market_value', sa.Float(), nullable=True),
    sa.Column('contract_expiration', sa.Date(), nullable=True),
    sa.Column('per90', sa.JSON(), nullable=False),
    sa.Column('shrunk_per90', sa.JSON(), nullable=False),
    sa.Column('percentiles', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('player_id')
    )
    with op.batch_alter_table('player_season_agg', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_season_agg_perf_index'), ['perf_index'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_season_agg_position_group'), ['position_group'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_season_agg_team_id'), ['team_id'], unique=False)

    op.create_table('similar_players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_run_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('similar_player_id', sa.Integer(), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'similar_player_id')
    )
    with op.batch_alter_table('similar_players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_similar_players_player_id'), ['player_id'], unique=False)

    op.create_table('team_strength',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('model_run_id', sa.Integer(), nullable=False),
    sa.Column('attack', sa.Float(), nullable=False),
    sa.Column('defence', sa.Float(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('played', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('xpts', sa.Float(), nullable=False),
    sa.Column('goals_for', sa.Integer(), nullable=False),
    sa.Column('goals_against', sa.Integer(), nullable=False),
    sa.Column('avg_player_rating', sa.Float(), nullable=True),
    sa.Column('squad_value', sa.Float(), nullable=True),
    sa.Column('series', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_table('tm_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('club_name', sa.String(length=160), nullable=True),
    sa.Column('competition_id', sa.String(length=10), nullable=True),
    sa.Column('position', sa.String(length=40), nullable=True),
    sa.Column('sub_position', sa.String(length=40), nullable=True),
    sa.Column('contract_expiration', sa.Date(), nullable=True),
    sa.Column('market_value', sa.Float(), nullable=True),
    sa.Column('image_url', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tm_players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tm_players_birth_date'), ['birth_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_tm_players_competition_id'), ['competition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tm_players_name'), ['name'], unique=False)

    op.create_table('valuations',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('model_run_id', sa.Integer(), nullable=False),
    sa.Column('market_value', sa.Float(), nullable=False),
    sa.Column('p10', sa.Float(), nullable=False),
    sa.Column('p50', sa.Float(), nullable=False),
    sa.Column('p90', sa.Float(), nullable=False),
    sa.Column('undervalue_score', sa.Float(), nullable=False),
    sa.Column('below_p10', sa.Boolean(), nullable=False),
    sa.Column('contributions', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('player_id')
    )
    with op.batch_alter_table('valuations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_valuations_undervalue_score'), ['undervalue_score'], unique=False)

    op.create_table('coach_tenures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('start', sa.Date(), nullable=True),
    sa.Column('end', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coach_id', 'team_id', 'start')
    )
    with op.batch_alter_table('coach_tenures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coach_tenures_coach_id'), ['coach_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coach_tenures_team_id'), ['team_id'], unique=False)

    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('logo', sa.String(length=300), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fixtures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('round', sa.String(length=60), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('home_goals', sa.Integer(), nullable=True),
    sa.Column('away_goals', sa.Integer(), nullable=True),
    sa.Column('player_stats_synced', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fixtures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fixtures_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_fixtures_league_id'), ['league_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fixtures_season'), ['season'], unique=False)

    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('firstname', sa.String(length=120), nullable=True),
    sa.Column('lastname', sa.String(length=120), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('nationality', sa.String(length=80), nullable=True),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('photo', sa.String(length=300), nullable=True),
    sa.Column('position', sa.String(length=20), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_players_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_team_id'), ['team_id'], unique=False)

    op.create_table('player_match_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=120), nullable=True),
    sa.Column('position', sa.String(length=2), nullable=True),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('substitute', sa.Boolean(), nullable=False),
    sa.Column('captain', sa.Boolean(), nullable=False),
    sa.Column('api_rating', sa.Float(), nullable=True),
    sa.Column('offsides', sa.Integer(), nullable=False),
    sa.Column('shots_total', sa.Integer(), nullable=False),
    sa.Column('shots_on', sa.Integer(), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('conceded', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('saves', sa.Integer(), nullable=False),
    sa.Column('passes_total', sa.Integer(), nullable=False),
    sa.Column('passes_key', sa.Integer(), nullable=False),
    sa.Column('passes_accurate', sa.Integer(), nullable=False),
    sa.Column('tackles', sa.Integer(), nullable=False),
    sa.Column('blocks', sa.Integer(), nullable=False),
    sa.Column('interceptions', sa.Integer(), nullable=False),
    sa.Column('duels_total', sa.Integer(), nullable=False),
    sa.Column('duels_won', sa.Integer(), nullable=False),
    sa.Column('dribbles_attempts', sa.Integer(), nullable=False),
    sa.Column('dribbles_success', sa.Integer(), nullable=False),
    sa.Column('dribbled_past', sa.Integer(), nullable=False),
    sa.Column('fouls_drawn', sa.Integer(), nullable=False),
    sa.Column('fouls_committed', sa.Integer(), nullable=False),
    sa.Column('yellow', sa.Integer(), nullable=False),
    sa.Column('red', sa.Integer(), nullable=False),
    sa.Column('pen_won', sa.Integer(), nullable=False),
    sa.Column('pen_committed', sa.Integer(), nullable=False),
    sa.Column('pen_scored', sa.Integer(), nullable=False),
    sa.Column('pen_missed', sa.Integer(), nullable=False),
    sa.Column('pen_saved', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fixture_id', 'player_id')
    )
    with op.batch_alter_table('player_match_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_match_stats_fixture_id'), ['fixture_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_match_stats_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_match_stats_team_id'), ['team_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_match_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_match_stats_team_id'))
        batch_op.drop_index(batch_op.f('ix_player_match_stats_player_id'))
        batch_op.drop_index(batch_op.f('ix_player_match_stats_fixture_id'))

    op.drop_table('player_match_stats')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_team_id'))
        batch_op.drop_index(batch_op.f('ix_players_name'))

    op.drop_table('players')
    with op.batch_alter_table('fixtures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fixtures_season'))
        batch_op.drop_index(batch_op.f('ix_fixtures_league_id'))
        batch_op.drop_index(batch_op.f('ix_fixtures_date'))

    op.drop_table('fixtures')
    op.drop_table('teams')
    with op.batch_alter_table('coach_tenures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coach_tenures_team_id'))
        batch_op.drop_index(batch_op.f('ix_coach_tenures_coach_id'))

    op.drop_table('coach_tenures')
    with op.batch_alter_table('valuations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_valuations_undervalue_score'))

    op.drop_table('valuations')
    with op.batch_alter_table('tm_players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tm_players_name'))
        batch_op.drop_index(batch_op.f('ix_tm_players_competition_id'))
        batch_op.drop_index(batch_op.f('ix_tm_players_birth_date'))

    op.drop_table('tm_players')
    op.drop_table('team_strength')
    with op.batch_alter_table('similar_players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_similar_players_player_id'))

    op.drop_table('similar_players')
    with op.batch_alter_table('player_season_agg', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_season_agg_team_id'))
        batch_op.drop_index(batch_op.f('ix_player_season_agg_position_group'))
        batch_op.drop_index(batch_op.f('ix_player_season_agg_perf_index'))

    op.drop_table('player_season_agg')
    with op.batch_alter_table('player_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_links_tm_player_id'))

    op.drop_table('player_links')
    op.drop_table('player_link_overrides')
    with op.batch_alter_table('player_form', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_form_player_id'))

    op.drop_table('player_form')
    op.drop_table('model_runs')
    with op.batch_alter_table('match_ratings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_ratings_player_id'))
        batch_op.drop_index(batch_op.f('ix_match_ratings_model_run_id'))
        batch_op.drop_index(batch_op.f('ix_match_ratings_fixture_id'))

    op.drop_table('match_ratings')
    op.drop_table('match_predictions')
    with op.batch_alter_table('market_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_values_tm_player_id'))

    op.drop_table('market_values')
    with op.batch_alter_table('manager_ratings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_manager_ratings_score'))
        batch_op.drop_index(batch_op.f('ix_manager_ratings_coach_id'))

    op.drop_table('manager_ratings')
    op.drop_table('leagues')
    op.drop_table('coaches')
    with op.batch_alter_table('api_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_usage_day'))

    op.drop_table('api_usage')
    # ### end Alembic commands ###
